# Generated by Django 5.1.6 on 2025-05-20 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resource_requests", "0002_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="theme_preference",
            field=models.CharField(
                choices=[("light", "Light"), ("dark", "Dark")],
                default="light",
                max_length=10,
            ),
        ),
    ]
