# Generated by Django 5.1.6 on 2025-05-20 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resource_requests", "0003_userprofile_theme_preference"),
    ]

    operations = [
        migrations.AddField(
            model_name="resourcerequest",
            name="signature_image",
            field=models.ImageField(blank=True, null=True, upload_to="signatures/"),
        ),
        migrations.AddField(
            model_name="resourcerequest",
            name="stamp_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="signature",
            field=models.ImageField(blank=True, null=True, upload_to="signatures/"),
        ),
    ]
